import { useEffect, useState } from "react";
import { GitBranch, Award, Code, CheckCircle, Lightbulb } from "lucide-react";
import { api } from "../../services/api";

interface GithubAnalyticsData {
  profilesAnalyzed: number;
  averagePortfolioScore: number;
  mostCommonTechnologies: string[];
  commonRecommendations: string[];
}

export function AdminGitHubPage() {
  const [data, setData] = useState<GithubAnalyticsData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api
      .get("/admin/github")
      .then((res) => setData(res.data))
      .catch((err) => console.error("Error loading GitHub analytics:", err))
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <div className="admin-loading-state">
        <div className="admin-spinner" />
        <p>Parsing developer portfolio telemetry...</p>
      </div>
    );
  }

  const {
    profilesAnalyzed,
    averagePortfolioScore,
    mostCommonTechnologies,
    commonRecommendations,
  } = data || {
    profilesAnalyzed: 0,
    averagePortfolioScore: 74,
    mostCommonTechnologies: [],
    commonRecommendations: [],
  };

  return (
    <div className="admin-page-container">
      <div className="admin-page-header">
        <div>
          <h2>GitHub Portfolio Analytics</h2>
          <p className="admin-page-sub">Repository quality scores, stack distribution, and recurring codebase advice.</p>
        </div>
        <div className="admin-user-count-badge">Analyzed: {profilesAnalyzed}</div>
      </div>

      <div className="admin-kpi-row">
        <div className="admin-kpi-card">
          <div className="kpi-icon-wrapper" style={{ color: "#2563eb", background: "rgba(37,99,235,0.1)" }}>
            <GitBranch size={22} />
          </div>
          <div>
            <span className="kpi-label">Profiles Analyzed</span>
            <strong className="kpi-value">{profilesAnalyzed}</strong>
          </div>
        </div>

        <div className="admin-kpi-card">
          <div className="kpi-icon-wrapper" style={{ color: "#059669", background: "rgba(5,150,105,0.1)" }}>
            <Award size={22} />
          </div>
          <div>
            <span className="kpi-label">Avg Portfolio Score</span>
            <strong className="kpi-value">{averagePortfolioScore}%</strong>
          </div>
        </div>
      </div>

      <div className="admin-analytics-grid">
        {/* Most Common Tech */}
        <div className="admin-card">
          <div className="admin-card-head">
            <div>
              <h3>Most Common Tech & Languages</h3>
              <p className="admin-card-sub">Dominant programming languages detected across scanned repositories</p>
            </div>
            <div className="admin-badge-subtle">
              <Code size={14} /> Languages
            </div>
          </div>

          <div className="skills-tags-cluster">
            {mostCommonTechnologies.map((tech, index) => (
              <span key={index} className="admin-skill-chip detected">
                <span className="chip-rank">#{index + 1}</span> {tech}
              </span>
            ))}
          </div>
        </div>

        {/* Common Recommendations */}
        <div className="admin-card">
          <div className="admin-card-head">
            <div>
              <h3>Common GitHub Portfolio Advice</h3>
              <p className="admin-card-sub">Frequent suggestions generated by AI portfolio auditor</p>
            </div>
            <div className="admin-badge-subtle" style={{ color: "#d97706" }}>
              <Lightbulb size={14} /> AI Coaching
            </div>
          </div>

          <div className="recommendations-list">
            {commonRecommendations.map((rec, index) => (
              <div key={index} className="recommendation-item">
                <CheckCircle size={16} color="#059669" className="rec-icon" />
                <p className="rec-text">{rec}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
